import { Lesson } from './course';

export const hypnosisLessons: Lesson[] = [
  {
    id: 1,
    title: 'What Hypnosis Is—and Is Not',
    summary: 'Build a practical model of hypnosis based on attention, expectation, imagination, absorption and voluntary responsiveness.',
    duration: '35–50 min', level: 'Foundation',
    objectives: ['Explain hypnosis without myths about sleep or mind control.', 'Recognise expectation, context and imagination as major ingredients.', 'Treat responsiveness as variable rather than pass/fail.'],
    sections: [
      { heading: 'A useful working model', body: ['Hypnosis is a structured situation in which a person focuses attention, engages imagination and responds to suggestions. Responses can feel automatic even though the participant remains able to think, speak and stop.', 'No single theory explains every hypnotic response. Expectation, absorption, motivation, social context and learned response all contribute. The practical skill is guiding attention and suggestion, not claiming a mysterious power.'] },
      { heading: 'Automaticity without mythology', body: ['The interesting feature of a successful suggestion is often the feeling that a movement, sensation or thought is happening by itself. Small changes are enough to build on.', 'Hypnosis is not ordinary sleep, truth serum or guaranteed obedience. A person may respond strongly to movement suggestions yet weakly to amnesia; that difference is useful feedback, not failure.'] }
    ],
    procedure: ['Recall a normal experience of deep absorption such as a film, book or repetitive journey.', 'Identify narrowed attention, vivid imagery and reduced awareness of distractions.', 'Practise a 60-second explanation of hypnosis without the words control, unconscious or weak-minded.', 'Ask a partner what they think hypnosis is and correct only the myths that affect safety.', 'End by describing responsiveness as a skill that varies by person and suggestion.'],
    script: ['Hypnosis is guided attention and imagination. You remain able to hear me, think and stop at any time.', 'There is nothing to prove. Notice whatever changes occur, even if they are small.'],
    drills: ['Record three one-minute explanations: friendly, formal and performance styles.', 'Write one accurate correction for ten common hypnosis myths.'],
    troubleshooting: [{ problem: 'The explanation sounds too technical.', response: 'Use one ordinary absorption example and one sentence about consent, then begin an exercise.' }, { problem: 'A participant asks whether they can get stuck.', response: 'Explain that the session can be ended at any point and that all temporary suggestions will be explicitly cancelled.' }],
    ethics: ['Never claim hypnosis guarantees obedience, confession, recovered memory or medical improvement.', 'Never shame someone for weak or absent response.', 'Use this course for education, consensual demonstration and self-practice—not treatment.'],
    assignment: 'Deliver a 90-second explanation to a consenting adult, invite questions and rewrite any sentence that caused confusion.',
    quiz: [{ question: 'Which description is most accurate?', options: ['Unconscious sleep', 'Guided attention and suggestion with active participation', 'Truth serum', 'Loss of moral control'], answer: 1, explanation: 'Hypnosis involves attention, expectation, imagination and participation.' }, { question: 'A weak response is best treated as:', options: ['Resistance', 'Failure', 'Feedback for adapting the exercise', 'Proof hypnosis is fake'], answer: 2, explanation: 'Responses vary across people and suggestions.' }],
    media: ['Intro explainer video', 'Myth-versus-fact cards', 'Two-minute absorption audio']
  },
  {
    id: 2, title: 'Consent, Screening and Safety', summary: 'Create a repeatable safety process before any partner exercise, induction or performance demonstration.', duration: '40–55 min', level: 'Foundation',
    objectives: ['Obtain informed and specific consent.', 'Recognise obvious reasons not to proceed.', 'Prepare stop signals, physical safety, cancellation and debriefing.'],
    sections: [
      { heading: 'Consent is specific', body: ['A participant should know the general activity, likely duration and kinds of responses that may be suggested. Consent to relaxation does not automatically include amnesia, touch, filming or public performance.', 'Ask again when an activity changes materially. The participant can stop, speak, open their eyes or change position at any time.'] },
      { heading: 'Safe setting and exit', body: ['Do not practise with someone who appears intoxicated, acutely distressed, pressured by others or unable to understand the instructions. Avoid stairs, water, traffic, machinery and unstable standing positions.', 'Every temporary suggestion needs a removal step. Restore ordinary movement, memory, sensation and alertness, then ask the participant how they feel.'] }
    ],
    procedure: ['Explain the exercise and likely duration.', 'Ask whether the person is comfortable and wishes to continue.', 'Agree on a verbal or visible stop signal.', 'Check chair, floor and surrounding hazards.', 'State what will not be attempted.', 'Afterward cancel suggestions, reorient and debrief.'],
    script: ['This is voluntary. You can speak or stop at any point, and I will end the exercise immediately if you ask.', 'I will not use embarrassing, frightening or private suggestions. Is that acceptable?'],
    drills: ['Role-play consent for relaxation, hand levitation and a playful stage effect as separate conversations.', 'Create a ten-item physical-safety checklist.'],
    troubleshooting: [{ problem: 'Friends pressure someone to volunteer.', response: 'Decline that volunteer; willingness must come from the participant.' }, { problem: 'A participant becomes uncomfortable.', response: 'Stop, restore normal orientation and ask what support they want.' }],
    ethics: ['Never surprise-induce someone who has not already consented.', 'Never combine practice with alcohol or recreational drugs.', 'Do not film or publish a session without separate permission.'],
    assignment: 'Create a one-page consent, environment and debrief checklist and use it in every later partner exercise.',
    quiz: [{ question: 'Consent to relaxation automatically permits name amnesia.', options: ['True', 'False'], answer: 1, explanation: 'Materially different phenomena require specific consent.' }, { question: 'The first response to discomfort is:', options: ['Push through', 'Stop and reorient', 'Change volunteers', 'Increase intensity'], answer: 1, explanation: 'Participant welfare overrides performance goals.' }], media: ['Consent walkthrough', 'Printable safety checklist', 'Early-exit demonstration']
  },
  {
    id: 3, title: 'The Pre-Talk', summary: 'Create accurate expectations, reduce fear and make the participant’s role simple before any induction begins.', duration: '35–50 min', level: 'Foundation',
    objectives: ['Remove common fears without overexplaining.', 'Create a cooperative success frame.', 'Adapt the pre-talk to informal and performance settings.'],
    sections: [
      { heading: 'Four jobs of a pre-talk', body: ['Define hypnosis briefly, confirm agency, explain what the participant should do and create curiosity about automatic responses. A concise pre-talk usually works better than a lecture.', 'Ask what the participant already believes. Correct only misconceptions that affect safety or participation, then move into an experience.'] },
      { heading: 'Success without pressure', body: ['Avoid claims that only intelligent, creative or weak-minded people respond. Such statements create social pressure rather than useful expectation.', 'Invite the participant to follow, imagine and notice. Reinforce real changes such as slower breathing, finger movement or a sense of heaviness instead of pretending a response exists.'] }
    ],
    procedure: ['Ask what the participant currently believes about hypnosis.', 'Correct relevant misconceptions.', 'Explain that their role is to follow, imagine, allow and report.', 'Describe small responses as useful.', 'Confirm consent.', 'Begin before the explanation becomes a lecture.'],
    script: ['You do not need to force anything. Follow the instructions, imagine them as clearly as you comfortably can, and notice what starts to happen.', 'You will still hear me and can stop at any point. We will begin with something small.'],
    drills: ['Deliver 45-second, 90-second and three-minute versions.', 'Answer five common objections without becoming argumentative.'],
    troubleshooting: [{ problem: 'The pre-talk sounds like a sales pitch.', response: 'Remove claims about power and replace them with clear instructions and uncertainty.' }, { problem: 'You talk for ten minutes.', response: 'Return to the four jobs: define, agency, task, curiosity.' }],
    ethics: ['Never use fear or false authority to gain compliance.', 'Consent remains revocable after the induction starts.', 'Answer uncertainty honestly.'], assignment: 'Record your 90-second pre-talk and delete every sentence that does not improve safety, understanding or participation.',
    quiz: [{ question: 'The participant’s main task is to:', options: ['Obey', 'Pretend to sleep', 'Follow, imagine and notice', 'Prove suggestibility'], answer: 2, explanation: 'Clear participation instructions are more useful than pressure.' }, { question: 'A strong pre-talk establishes:', options: ['Dominance', 'Cooperation and accurate expectations', 'Fear of failure', 'Clinical authority'], answer: 1, explanation: 'Understanding and cooperation support responsiveness.' }], media: ['Calm pre-talk audio', 'Performance pre-talk video', 'Annotated transcript']
  },
  {
    id: 4, title: 'Ideomotor and Suggestibility Exercises', summary: 'Learn magnetic fingers, magnetic hands, light-and-heavy hands, pendulum movement and early hand levitation.', duration: '50–70 min', level: 'Beginner practical',
    objectives: ['Deliver concrete sensory suggestions.', 'Notice and reinforce small responses.', 'Use exercises as exploration rather than tests.'],
    sections: [
      { heading: 'Designing a suggestion', body: ['Good suggestions direct attention, provide an image, predict a small change and then reinforce genuine evidence. Sensory language—pressure, warmth, weight, pull, lift—gives imagination something specific to organise around.', 'Repetition should add detail rather than merely saying stronger and stronger. Allow enough silence for the participant to experience the suggestion.'] },
      { heading: 'Ideomotor response', body: ['Ideas and expectations can influence small muscular movements without a deliberate decision to move. Finger attraction and pendulum exercises demonstrate this elegantly.', 'Do not claim pendulum movement reveals objective hidden truth. It reflects expectation, attention and subtle movement and is best used as an experiential or theatrical tool.'] }
    ],
    procedure: ['Explain that the exercise is exploratory.', 'Set a stable posture and clear target.', 'Focus attention on one sensory image.', 'Allow 20–45 seconds before judging the response.', 'Reinforce actual changes precisely.', 'Cancel the exercise and ask what the participant noticed.'],
    script: ['Imagine a gentle magnetic pull between your fingertips. You may notice the gap narrowing, even slightly.', 'One hand can imagine a heavy book while the other imagines balloons. Notice any difference rather than trying to manufacture one.'],
    drills: ['Practise magnetic fingers, magnetic hands and light/heavy hands from memory.', 'Create visual and body-sensation versions of hand levitation.'],
    troubleshooting: [{ problem: 'Nothing visibly moves.', response: 'Ask about sensation, simplify the image and avoid declaring failure.' }, { problem: 'The participant deliberately moves.', response: 'Accept it, slow the exercise and invite attention to when movement begins to feel easier or more automatic.' }],
    ethics: ['Do not label suggestibility as intelligence, weakness or compliance.', 'Avoid prolonged arm positions that cause strain.', 'Restore normal movement after heaviness or inhibition suggestions.'], assignment: 'Run two simple exercises with three consenting adults and record wording, visible response and their subjective description.',
    quiz: [{ question: 'Ideomotor movement is best described as:', options: ['Hidden truth detection', 'Movement influenced by ideas and expectation', 'Paranormal force', 'Diagnosis'], answer: 1, explanation: 'Ideas and expectation can shape subtle muscular movement.' }, { question: 'If movement is small you should:', options: ['Call it failure', 'Increase pressure', 'Reinforce what actually occurred', 'Pretend it was large'], answer: 2, explanation: 'Accurate reinforcement builds trust and responsiveness.' }], media: ['Magnetic-fingers demo', 'Pendulum explainer', 'Practice timing guide']
  },
  {
    id: 5, title: 'The Architecture of an Induction', summary: 'Understand the reusable components behind eye-fixation, breathing, hand-focus, imagery and conversational inductions.', duration: '50–65 min', level: 'Beginner practical',
    objectives: ['Separate induction structure from memorised scripts.', 'Move from attention to response and absorption.', 'Adapt an induction when one sensory style does not fit.'],
    sections: [
      { heading: 'The induction sequence', body: ['A useful sequence is: secure attention, narrow the task, establish a small response, label and reinforce that response, then move into deeper absorption and simple suggestions.', 'The induction is not a magic doorway. It is an organised transition into focused responding. Once that is understood, different scripts become variations of the same structure.'] },
      { heading: 'Match the participant', body: ['Some people respond well to visual imagery, others to body sensation, breathing or analytical step-by-step instructions. Notice their language and adapt.', 'If eye closure does not happen dramatically, continue normally. Hypnosis does not depend on closed eyes, limp posture or a theatrical sleep command.'] }
    ],
    procedure: ['Choose one attention target.', 'Describe exactly what the participant should notice.', 'Elicit one small response.', 'Reinforce it without exaggeration.', 'Invite eyes closed only if comfortable.', 'Transition into a simple movement or relaxation suggestion.', 'End and debrief.'],
    script: ['Keep your attention on one point and simply notice the small changes in blinking, breathing and effort that happen when you focus for a while.', 'As you notice those changes, you can let the same focused feeling spread through the rest of the exercise.'],
    drills: ['Write eye-fixation, hand-focus and breathing inductions using the same six-step structure.', 'Practise switching from visual imagery to body sensation mid-induction.'],
    troubleshooting: [{ problem: 'You forget the script.', response: 'Return to the structure: attention, response, reinforce, absorb, suggest.' }, { problem: 'The participant keeps their eyes open.', response: 'Continue; eye closure is optional and can be invited later.' }],
    ethics: ['Do not imply the induction removes agency.', 'Do not physically manipulate the participant into posture.', 'Choose stable positions and avoid prolonged standing.'], assignment: 'Create and record a three-minute induction from the structural template rather than memorising a published script.',
    quiz: [{ question: 'An induction is best understood as:', options: ['A sleep command', 'An organised transition into focused responding', 'A loss of consciousness', 'A test of obedience'], answer: 1, explanation: 'The structure organises attention and suggestion.' }, { question: 'Closed eyes are:', options: ['Always required', 'Never allowed', 'Optional', 'Proof of trance depth'], answer: 2, explanation: 'Useful hypnosis can occur with eyes open or closed.' }], media: ['Three induction demonstrations', 'Induction architecture diagram', 'Audio practice track']
  },
  {
    id: 6, title: 'Rapid and Pattern-Interrupt Inductions', summary: 'Use surprise and redirected attention safely after explicit prior consent—without aggressive physical handling.', duration: '45–60 min', level: 'Intermediate',
    objectives: ['Explain why rapid inductions can work.', 'Use a brief interruption followed by clear instruction.', 'Handle laughter, non-response and balance safely.'],
    sections: [
      { heading: 'What makes rapid feel rapid', body: ['A rapid induction compresses expectation, focused attention and a clear transition. Surprise can interrupt an expected action for a moment, but the important part is the immediate, understood suggestion that follows.', 'Prior consent is essential. The surprise should be inside an agreed demonstration, not an ambush.'] },
      { heading: 'Safety before drama', body: ['Avoid jerking arms, pulling heads, pushing bodies or creating falls. A rapid induction can be performed seated or with stable support and minimal physical contact.', 'If the participant laughs or simply looks at you, treat it as normal. Continue with a slower focus instruction instead of pretending the interruption succeeded.'] }
    ],
    procedure: ['Explain and obtain consent for a rapid-style induction.', 'Choose a stable seated or supported position.', 'Set a familiar action and clear attention target.', 'Introduce a mild, safe interruption.', 'Immediately redirect attention to breathing, eyes or a hand.', 'Continue only if the participant is comfortable.', 'Reorient fully.'],
    script: ['We are going to use a quick change of attention. Nothing will happen without your participation, and you can stop immediately.', 'As that expectation changes, put all of your attention on this one instruction and let everything else become less important for a moment.'],
    drills: ['Practise the verbal transition without touching anyone.', 'Rehearse the same sequence seated with a partner who intentionally laughs or does not respond.'],
    troubleshooting: [{ problem: 'The participant laughs.', response: 'Acknowledge it and continue with ordinary focused breathing or hand attention.' }, { problem: 'You feel tempted to make the move more forceful.', response: 'Do not. Improve expectation, clarity and timing rather than physical intensity.' }],
    ethics: ['Never surprise-induce an unconsenting person.', 'Avoid neck manipulation, falls, pain and aggressive pulling.', 'Do not use rapid inductions as demonstrations of dominance.'], assignment: 'Design a consent-first seated rapid induction with a calm fallback path if the interruption produces no response.',
    quiz: [{ question: 'The main value of the interruption is:', options: ['Physical force', 'A brief change in expectation and attention', 'Pain', 'Loss of consciousness'], answer: 1, explanation: 'The interruption creates a moment for attention to be redirected.' }, { question: 'If the participant laughs you should:', options: ['Increase force', 'Continue calmly or switch methods', 'Call them resistant', 'End in embarrassment'], answer: 1, explanation: 'Laughter is normal and can be incorporated.' }], media: ['Seated rapid-induction demo', 'Timing breakdown', 'Fallback-path demonstration']
  },
  {
    id: 7, title: 'Deepeners and Fractionation', summary: 'Increase absorption using counting, imagery, repeated eye opening, breathing, hand lowering and participant-generated experience.', duration: '40–55 min', level: 'Intermediate',
    objectives: ['Use deepening as increased engagement rather than mystical depth.', 'Apply fractionation gently.', 'Choose deepeners that match the participant.'],
    sections: [{ heading: 'What deepening means', body: ['Deepening is a practical label for increasing absorption, comfort and responsiveness. It does not imply measurable descent into a universal trance scale.', 'Counting, imagined stairs, breathing and hand lowering work because they organise attention over time and give the participant repeated opportunities to respond.'] }, { heading: 'Fractionation', body: ['Repeatedly moving between slightly more and less absorbed states can make the contrast vivid. For example, invite the eyes open briefly, then close again while returning attention inward.', 'Keep the process short and comfortable. The goal is not exhaustion but clearer experiential contrast.'] }],
    procedure: ['Ask what sensations or images are already working.', 'Choose a matching deepener.', 'Link each count or movement to a specific experience.', 'Pause for response.', 'Use one or two brief cycles of fractionation if appropriate.', 'Test a simple suggestion rather than deepening endlessly.'],
    script: ['With each comfortable breath, let your attention become a little less interested in the room and a little more interested in what you are noticing inside.', 'Open your eyes for a moment, notice the contrast, and when you close them again return directly to that focused feeling.'], drills: ['Create counting, staircase, hand-lowering and breath-based versions.', 'Practise replacing the word deeper with concrete sensory descriptions.'],
    troubleshooting: [{ problem: 'The script becomes repetitive.', response: 'Change sensory detail or move to a useful suggestion.' }, { problem: 'The participant dislikes staircase imagery.', response: 'Use breathing, sound, hand movement or another neutral focus.' }], ethics: ['Avoid imagery associated with fear, confinement or trauma.', 'Do not equate stillness with success.', 'Stop if the participant becomes uncomfortable or disoriented.'], assignment: 'Record two three-minute deepeners using different sensory styles and no more than three uses of the word deeper.',
    quiz: [{ question: 'Deepening primarily aims to increase:', options: ['Unconsciousness', 'Absorption and responsiveness', 'Physical weakness', 'Obedience'], answer: 1, explanation: 'It organises attention and engagement.' }, { question: 'Fractionation means:', options: ['Forgetting names', 'Moving between more and less absorbed states', 'Using pain', 'Rapid speech'], answer: 1, explanation: 'Contrast can strengthen the subjective experience.' }], media: ['Breathing deepener audio', 'Fractionation demonstration', 'Deepener selection chart']
  },
  {
    id: 8, title: 'The Hypnotic Phenomena Ladder', summary: 'Progress from simple ideomotor responses toward catalepsy, inhibition, amnesia and vivid imaginative experiences.', duration: '55–70 min', level: 'Intermediate',
    objectives: ['Sequence suggestions from easier to more demanding.', 'Build later phenomena from genuine earlier responses.', 'Know when to stop escalating.'],
    sections: [{ heading: 'Build, do not jump', body: ['A useful progression is movement, heaviness or lightness, catalepsy, harmless temporary inhibition, altered sensation, simple amnesia and then more vivid imaginative phenomena.', 'The order is not rigid, but later suggestions should emerge from evidence of what the participant already does well.'] }, { heading: 'Ratify success', body: ['When a response occurs, draw attention to the aspect that felt automatic and use it as evidence for the next suggestion. This creates continuity rather than a series of unrelated tests.', 'If response weakens, step back to something successful or end on a positive experience. Do not make the session a battle of increasingly extreme tests.'] }],
    procedure: ['Begin with a simple movement response.', 'Identify the participant’s strongest modality.', 'Build one level at a time.', 'Test gently.', 'Cancel each temporary effect before moving on when appropriate.', 'Stop escalating when comfort or engagement drops.', 'Finish with a clean reorientation.'],
    script: ['That small movement happened more easily than you expected. Use that same automatic feeling with the next suggestion.', 'There is no need to make this stronger than comfortable; we are exploring how your imagination responds.'], drills: ['Design three different phenomenon ladders for movement-dominant, imagery-dominant and analytical participants.', 'Practise stepping backward gracefully after a miss.'],
    troubleshooting: [{ problem: 'You jump directly to amnesia after weak ideomotor response.', response: 'Return to a phenomenon the participant already experiences reliably.' }, { problem: 'Every suggestion is framed as a challenge.', response: 'Use exploration language and remove pass/fail tests.' }], ethics: ['Never escalate because an audience demands something more extreme.', 'Do not use pain, dangerous posture or humiliating content.', 'Cancel temporary effects explicitly.'], assignment: 'Write a six-stage ladder with a fallback at every stage and rehearse the transitions aloud.',
    quiz: [{ question: 'The best next suggestion usually builds on:', options: ['Audience pressure', 'A previous genuine response', 'A random script', 'Physical force'], answer: 1, explanation: 'Continuity improves both safety and responsiveness.' }, { question: 'If response weakens:', options: ['Escalate', 'Step back or end positively', 'Shame the participant', 'Repeat louder'], answer: 1, explanation: 'Adaptation is more effective than pressure.' }], media: ['Phenomena ladder diagram', 'Three participant examples', 'Fallback decision tree']
  },
  {
    id: 9, title: 'Catalepsy, Sticking and Harmless Inhibition', summary: 'Create temporary experiences such as a rigid arm, stuck hand or fingers that briefly feel locked—then remove them cleanly.', duration: '50–65 min', level: 'Intermediate',
    objectives: ['Build inhibition from sensation and expectation.', 'Test gently without turning suggestions into contests.', 'Restore normal movement immediately after the effect.'],
    sections: [{ heading: 'From movement to non-movement', body: ['Inhibition suggestions often work best when they grow from a positive sensation: heaviness, pressure, stillness or the idea that movement would require unnecessary effort.', 'Phrase the test as an opportunity to notice the effect, not a command to fight against it. The harder someone strains, the more the exercise can turn into a strength contest.'] }, { heading: 'Cancellation is part of the method', body: ['Every inhibition should contain an explicit release cue. After release, ask the participant to move normally and confirm comfort.', 'Avoid full-body immobilisation, unsafe standing tests or anything that could create a fall. Hands, fingers and supported arms are sufficient for strong demonstrations.'] }],
    procedure: ['Obtain consent for the exact temporary effect.', 'Establish heaviness, stillness or rigidity first.', 'Suggest temporary difficulty moving.', 'Invite only a gentle test.', 'Reinforce the experience if present.', 'Give a clear release cue.', 'Verify normal movement.'],
    script: ['Notice how still that hand can become, as though it has decided there is no reason to move for the next few seconds.', 'In a moment I will say release. When I do, all of that suggestion ends and the hand moves normally and comfortably.'], drills: ['Practise hand-stick, finger-lock and supported arm-catalepsy wording.', 'Rehearse release cues until they are automatic.'], troubleshooting: [{ problem: 'The participant strains hard.', response: 'Stop the test, release the suggestion and later use a gentler noticing instruction.' }, { problem: 'Movement remains slightly awkward after release.', response: 'Repeat the cancellation, invite normal stretching and confirm full comfort before continuing.' }], ethics: ['Never use inhibition near stairs, traffic or unstable surfaces.', 'Do not invite painful tests or weight-bearing stunts.', 'Always verify complete release.'], assignment: 'Create a two-minute hand-stick demonstration with consent, gentle test, release and debrief.',
    quiz: [{ question: 'A good inhibition test should be:', options: ['A strength contest', 'Gentle and brief', 'Painful', 'Performed without a release cue'], answer: 1, explanation: 'The goal is an experience, not physical struggle.' }, { question: 'Cancellation should happen:', options: ['Only if asked', 'Explicitly after the effect', 'Hours later', 'Never'], answer: 1, explanation: 'Temporary suggestions should be clearly removed.' }], media: ['Hand-stick demo', 'Release-cue practice audio', 'Safety positioning graphic']
  },
  {
    id: 10, title: 'Temporary Amnesia and Name Forgetting', summary: 'Explore reversible forgetting effects using neutral information, clear consent and complete restoration.', duration: '55–70 min', level: 'Advanced',
    objectives: ['Build amnesia from simpler responses.', 'Use neutral, short-lived targets.', 'Restore recall and confidence completely.'],
    sections: [{ heading: 'Forgetting as a suggested experience', body: ['Amnesia suggestions work better when framed as temporary inaccessibility rather than deletion: a number can feel skipped, a word can seem just out of reach or a label can briefly fail to arrive.', 'Start with trivial material. A missing number during counting is safer and easier to understand than personal or emotionally meaningful memories.'] }, { heading: 'Restoration and debrief', body: ['Tell the participant before the effect that recall will return fully on a clear cue. Deliver that cue, verify the target is available again and ask how the temporary forgetting felt.', 'Never encourage confabulated recovered memories or imply that hypnosis can establish historical truth. Memory is reconstructive and suggestible.'] }],
    procedure: ['Confirm consent specifically for temporary forgetting.', 'Begin with a neutral target such as a number or ordinary word.', 'Link forgetting to an image such as a blank label or closed drawer.', 'Test briefly.', 'Release immediately if frustration appears.', 'Restore the item clearly.', 'Verify normal recall and debrief.'],
    script: ['For only a few seconds, imagine that the number has stepped out of the sequence—nothing erased, simply unavailable until I say restore.', 'Restore. The number and all ordinary memory return clearly now.'], drills: ['Write three metaphors for temporary inaccessibility that do not imply damage.', 'Practise a complete restore-and-verify sequence.'], troubleshooting: [{ problem: 'The participant becomes frustrated.', response: 'Release immediately and move to a successful, comfortable phenomenon.' }, { problem: 'Recall does not feel fully normal after the cue.', response: 'Repeat the restoration explicitly, orient to the room and verify the target conversationally.' }], ethics: ['Do not target traumatic, intimate or consequential memories.', 'Do not use hypnosis to recover supposedly hidden memories.', 'Always restore and verify recall.'], assignment: 'Design a neutral number-forgetting demonstration with a written consent line and a scripted restoration.',
    quiz: [{ question: 'The safest initial amnesia target is:', options: ['Trauma', 'A neutral number or word', 'A password', 'A private memory'], answer: 1, explanation: 'Use trivial, reversible material.' }, { question: 'Hypnotic memory recovery should be treated as:', options: ['Historical proof', 'Highly reliable', 'Potentially suggestible and not proof', 'A lie detector'], answer: 2, explanation: 'Memory can be distorted by suggestion.' }], media: ['Number-amnesia demonstration', 'Restoration checklist', 'Memory caution explainer']
  },
  {
    id: 11, title: 'Sensory Change and Imaginative Experience', summary: 'Guide changes in heaviness, warmth, taste, sound and vivid imagery while keeping suggestions pleasant and reversible.', duration: '50–65 min', level: 'Advanced',
    objectives: ['Use multi-sensory language.', 'Scale from subtle sensation to vivid imagination.', 'Avoid frightening or unsafe hallucination content.'],
    sections: [{ heading: 'Sensory suggestion', body: ['Attention changes experience. A hand can feel warmer when attention is directed to warmth; an ordinary object can feel surprisingly heavy when expectation is organised around weight.', 'Begin with changes that remain compatible with the environment. The participant does not need to lose contact with reality for an effect to feel vivid and surprising.'] }, { heading: 'Positive imaginative phenomena', body: ['For stronger responders, imagery can be invited as if a sound, smell or visual detail were unusually vivid. Use pleasant, neutral content and keep the participant oriented.', 'Avoid negative hallucination involving real hazards—for example suggesting that a chair, person or obstacle is invisible. Theatrical impact is never worth physical risk.'] }],
    procedure: ['Select a pleasant neutral sensation.', 'Establish baseline experience.', 'Direct attention to one sensory dimension.', 'Layer image, expectation and repetition.', 'Ask for a subjective report rather than forcing a test.', 'Cancel the suggestion.', 'Confirm ordinary perception.'], script: ['Notice the ordinary temperature of your hand first. Now imagine warmth spreading slowly from the centre of the palm, and simply compare the difference.', 'When I say clear, the imagined quality fades and everything feels completely ordinary again.'], drills: ['Write visual, auditory, temperature and weight suggestions.', 'Practise returning from vivid imagery to full room orientation.'], troubleshooting: [{ problem: 'The participant reports nothing.', response: 'Reduce the goal to subtle comparison and switch sensory channels.' }, { problem: 'Imagery becomes uncomfortable.', response: 'Cancel immediately, orient to neutral sensory facts and debrief.' }], ethics: ['Do not create fear, humiliation or perceptions that hide real hazards.', 'Avoid suggestions involving pain or medical symptoms.', 'Restore ordinary perception clearly.'], assignment: 'Guide a consenting partner through two subtle sensory changes and record which sensory language they found easiest.',
    quiz: [{ question: 'A safe sensory progression begins with:', options: ['Threatening hallucinations', 'Subtle neutral changes', 'Ignoring hazards', 'Pain'], answer: 1, explanation: 'Small neutral changes are safer and easier to calibrate.' }, { question: 'Negative hallucination is risky when it:', options: ['Uses imagination', 'Could hide a real hazard', 'Is brief', 'Is discussed theoretically'], answer: 1, explanation: 'Physical safety must remain visible and intact.' }], media: ['Warmth/heaviness audio', 'Sensory-language worksheet', 'Reorientation demo']
  },
  {
    id: 12, title: 'Post-Hypnotic Suggestions', summary: 'Design benign, short-lived cue-and-response suggestions with explicit duration, consent, testing and removal.', duration: '45–60 min', level: 'Advanced',
    objectives: ['Specify cue, response and duration precisely.', 'Use only harmless agreed responses.', 'Remove and verify every post-hypnotic suggestion.'],
    sections: [{ heading: 'Cue, response, boundary', body: ['A post-hypnotic suggestion links a later cue to a response after the formal exercise has ended. Good design is specific: what cue, what response, how long it remains active and how it will be removed.', 'Use benign responses such as taking a slow breath, briefly smiling or re-entering a chosen relaxation exercise. Avoid anything deceptive, sexual, financial, coercive or consequential.'] }, { heading: 'Test and remove', body: ['Test the suggestion once in the agreed context, then remove it unless the participant explicitly wants a self-hypnosis cue to retain. State the removal clearly and verify that the cue no longer produces the response.', 'A suggestion is not a licence to bypass later consent. The participant remains free to ignore or stop responding to it.'] }],
    procedure: ['Agree on a harmless cue and response.', 'Define duration.', 'Install the suggestion in simple language.', 'Rehearse the cue once.', 'Test once after reorientation.', 'Remove explicitly.', 'Test removal if appropriate.'], script: ['For this demonstration only, when I tap the table once you can notice a brief urge to smile; you remain free to ignore it.', 'That cue is now cancelled completely. It has no further special meaning.'], drills: ['Write five benign cue-response pairs.', 'Practise concise removal language.'], troubleshooting: [{ problem: 'The response continues after removal.', response: 'Repeat cancellation, explain the cue is ordinary again and verify conversationally.' }, { problem: 'The cue is ambiguous.', response: 'Choose a distinctive cue unlikely to occur accidentally.' }], ethics: ['Never install sexual, coercive, financial or humiliating suggestions.', 'Do not use post-hypnotic cues to bypass fresh consent.', 'Remove temporary cues clearly.'], assignment: 'Create a complete cue-response-duration-removal script for a harmless two-minute demonstration.',
    quiz: [{ question: 'A well-designed post-hypnotic suggestion specifies:', options: ['Only the cue', 'Cue, response, duration and removal', 'Secret manipulation', 'Permanent obedience'], answer: 1, explanation: 'Clarity makes the suggestion bounded and testable.' }, { question: 'A participant can still ignore the cue.', options: ['True', 'False'], answer: 0, explanation: 'Hypnosis does not remove agency.' }], media: ['Cue-response demonstration', 'Design worksheet', 'Removal verification clip']
  },
  {
    id: 13, title: 'Conversational Hypnosis and Naturalistic Suggestion', summary: 'Use attention, pacing, metaphor, permissive language and participant-generated imagery without exaggerated NLP claims.', duration: '55–70 min', level: 'Advanced',
    objectives: ['Guide focused experience without a formal sleep-style induction.', 'Use pacing and leading accurately.', 'Distinguish consensual suggestion from covert control claims.'],
    sections: [{ heading: 'Naturalistic structure', body: ['Conversational hypnosis can begin with observable facts—breathing, posture, sounds in the room—then gradually direct attention toward imagery, memory or sensation. This is pacing followed by leading in its simplest form.', 'Metaphor can help when it gives the participant a useful way to organise experience. It is not a hidden command that automatically overrides judgement.'] }, { heading: 'Permissive language', body: ['Phrases such as you may notice, you can allow or some people find reduce unnecessary struggle and invite observation. Direct language can also work when consent and expectations are clear.', 'Use the participant’s own descriptive words whenever possible. Their language usually evokes richer experience than a stock script.'] }],
    procedure: ['Agree on the goal of the exercise.', 'Begin with three observable present-moment facts.', 'Invite one internal observation.', 'Use the participant’s own words to elaborate it.', 'Introduce a metaphor or future image.', 'Return attention to the room and debrief.'], script: ['You can notice the chair supporting you, the sound in the room and the ordinary rhythm of breathing. As those remain in the background, you may find one image becoming easier to focus on.', 'Use whatever words fit your experience; I will follow those rather than asking you to pretend mine are correct.'], drills: ['Guide two minutes of focused imagery without saying sleep or trance.', 'Rewrite ten exaggerated NLP claims into accurate attention-and-suggestion language.'], troubleshooting: [{ problem: 'Your language becomes vague word salad.', response: 'Return to observable facts and one concrete sensory target.' }, { problem: 'You assume every metaphor fits.', response: 'Ask the participant what image or description works for them.' }], ethics: ['Do not market conversational hypnosis as secret control.', 'Do not hide consequential persuasion inside a hypnosis exercise.', 'Keep goals explicit and consensual.'], assignment: 'Guide a five-minute naturalistic imagery exercise and transcribe which phrases produced the clearest participant responses.',
    quiz: [{ question: 'Pacing begins with:', options: ['False claims', 'Observable or accepted experience', 'Commands to obey', 'Confusion'], answer: 1, explanation: 'Accurate pacing builds continuity with present experience.' }, { question: 'Metaphor should be treated as:', options: ['Automatic mind control', 'A way to organise experience', 'A lie detector', 'Medical treatment'], answer: 1, explanation: 'Metaphor supports imagination but does not override agency.' }], media: ['Conversational demo', 'Pacing-leading worksheet', 'Annotated transcript']
  },
  {
    id: 14, title: 'Self-Hypnosis and Mental Rehearsal', summary: 'Build a short personal practice for relaxation, concentration, performance rehearsal and confidence without medical promises.', duration: '45–60 min', level: 'Practical',
    objectives: ['Create a repeatable self-induction.', 'Write realistic suggestions.', 'Use imagery to rehearse chosen behaviour.'],
    sections: [{ heading: 'A simple self-hypnosis loop', body: ['Choose one modest goal, settle attention, use breathing or fixation, deepen focus for a few minutes, rehearse the desired behaviour and then reorient fully.', 'Short frequent practice is usually more useful than dramatic sessions. Track whether behaviour actually changes rather than rating how deep the trance felt.'] }, { heading: 'Writing useful suggestions', body: ['Suggestions should be specific, positive, believable and linked to actions under your control. Instead of I will never feel nervous, rehearse slowing the first breath, looking at the audience and delivering the opening sentence calmly.', 'Self-hypnosis is not a substitute for professional care for medical or psychiatric conditions. Keep the course within rehearsal, relaxation and ordinary skill practice.'] }],
    procedure: ['Select one behavioural goal.', 'Write a concrete success scene.', 'Use two minutes of breathing or fixation.', 'Count down or use a familiar focus cue.', 'Rehearse the scene with sensory detail.', 'State one short action-oriented suggestion.', 'Count up, move and reorient.', 'Track real-world follow-through.'], script: ['For the next few minutes I am rehearsing one specific behaviour: beginning calmly, breathing once and taking the first useful action.', 'At five I am fully alert, ordinary and ready to continue the day.'], drills: ['Create five action-based suggestions from vague goals.', 'Practise five-minute and ten-minute versions.'], troubleshooting: [{ problem: 'You keep checking whether you are deep enough.', response: 'Judge the practice by focus and later behaviour, not trance theatrics.' }, { problem: 'The goal is too broad.', response: 'Reduce it to one observable action in one context.' }], ethics: ['Do not promise cure, diagnosis or treatment.', 'Never practise while driving or operating machinery.', 'Stop if practice causes distress or disorientation.'], assignment: 'Use a seven-minute self-hypnosis routine for one week and record the target behaviour, not just subjective depth.',
    quiz: [{ question: 'The best self-suggestion is usually:', options: ['Absolute and grandiose', 'Specific and action-oriented', 'Medical', 'Based on fear'], answer: 1, explanation: 'Concrete behaviours are easier to rehearse and evaluate.' }, { question: 'Success is best measured by:', options: ['How sleepy you felt', 'Relevant real-world behaviour', 'How long your eyes were closed', 'Dramatic sensations'], answer: 1, explanation: 'The practice is useful when it supports the intended behaviour.' }], media: ['Seven-minute self-hypnosis audio', 'Goal worksheet', 'Weekly practice tracker']
  },
  {
    id: 15, title: 'A Complete Safe Hypnosis Demonstration', summary: 'Assemble consent, pre-talk, responsiveness exercises, induction, phenomena, cancellation, reorientation and debrief into one professional sequence.', duration: '70–90 min', level: 'Capstone',
    objectives: ['Plan a coherent demonstration from start to finish.', 'Use fallback paths instead of forcing phenomena.', 'End with complete restoration and participant dignity.'],
    sections: [{ heading: 'The demonstration arc', body: ['A strong short sequence can be: consent and pre-talk, magnetic fingers, hand levitation, induction, brief deepening, one movement phenomenon, one harmless temporary inhibition, cancellation and reorientation.', 'Every step earns the next. If a response is weak, use a simpler phenomenon or end on something that worked. The performance should never depend on embarrassing the participant.'] }, { heading: 'Professional ending', body: ['Cancel all temporary suggestions explicitly, restore ordinary movement, sensation and memory, count or cue the participant back to normal alertness and ask how they feel.', 'Debrief without telling them what they were supposed to experience. Their description provides the best feedback for improving your wording and pacing.'] }],
    procedure: ['Check environment and obtain specific consent.', 'Deliver the pre-talk.', 'Run one ideomotor exercise.', 'Choose an induction matched to the response.', 'Use a short deepener.', 'Perform one or two suitable phenomena.', 'Cancel every suggestion.', 'Reorient fully.', 'Debrief and record learning notes.'], script: ['We will keep this short and comfortable. If any step is not enjoyable, we simply change it or stop.', 'Everything suggested during this demonstration is now cancelled. Movement, memory, sensation and attention are completely ordinary again.'], drills: ['Rehearse the entire sequence with an imaginary non-responsive participant.', 'Create fallback A, B and C for every phenomenon.'], troubleshooting: [{ problem: 'You forget the next step.', response: 'Return to comfort, cancel current suggestions and either choose a simple known effect or end cleanly.' }, { problem: 'The audience wants a more extreme stunt.', response: 'Decline and keep the planned safety boundary.' }], ethics: ['Participant welfare outranks entertainment value.', 'Never use dangerous stunts, humiliation or coercive content.', 'Always finish with full cancellation, reorientation and debrief.'], assignment: 'Record a complete ten-minute consent-first demonstration, then review safety, clarity, pacing, response quality and the ending.',
    quiz: [{ question: 'The defining professional skill is:', options: ['Forcing spectacular phenomena', 'Adapting respectfully to the participant', 'Using the fastest induction', 'Keeping every suggestion secret'], answer: 1, explanation: 'Good hypnosis practice adapts to real responses while protecting dignity and safety.' }, { question: 'A session should end with:', options: ['An unresolved suggestion', 'Cancellation, reorientation and debrief', 'A surprise stunt', 'Immediate departure'], answer: 1, explanation: 'A clean ending verifies ordinary functioning and comfort.' }], media: ['Full ten-minute demonstration', 'Capstone checklist', 'Self-review scorecard']
  }
];
