import { Lesson } from './course';

export const magicLessons: Lesson[] = [
  {
    id: 1, title: 'Constructing an Impossible Effect', summary: 'Learn to separate effect, method, presentation, convincers, cancellation and the spectator’s final remembered experience.', duration: '45–60 min', level: 'Foundation',
    objectives: ['Define an effect in one clean sentence.', 'Cancel likely explanations without over-proving fairness.', 'Design the reveal around clarity and emotion.'],
    sections: [{ heading: 'Effect before method', body: ['The audience remembers an event, not a sequence of secret moves. Start by writing the impossible sentence: a thought appears in writing, a prediction matches a free-looking decision or an object moves without contact.', 'Only after the effect is clear should you choose a method. This prevents routines from becoming technical demonstrations with no memorable climax.'] }, { heading: 'Convincers and cancellation', body: ['A convincer strengthens one condition: the envelope remained visible, the object was borrowed or the participant handled the paper. Cancellation removes an explanation by structure or timing.', 'Do not prove everything. Excessive fairness displays can create suspicion. Identify the two explanations spectators are most likely to consider and quietly eliminate those.'] }],
    procedure: ['Write the audience-facing effect in twelve words or fewer.', 'List every plausible explanation.', 'Rank the three explanations most likely to occur to spectators.', 'Add one natural convincer.', 'Cancel a second explanation through timing or structure.', 'Remove any procedure that does not strengthen the effect.', 'Ask a test viewer what they remember ten minutes later.'],
    script: ['Before you decide, I will leave one folded card here and we will not make it important yet.', 'The strange part is not only that it matches; it is that your decision came after the prediction was already beyond my reach.'],
    drills: ['Reverse-engineer three tricks into effect, method, convincers and remembered experience.', 'Describe each effect in one sentence without mentioning props.'], troubleshooting: [{ problem: 'The explanation is longer than the effect.', response: 'Reduce the routine to one decision, one impossible condition and one reveal.' }, { problem: 'You prove every prop ordinary.', response: 'Demonstrate only conditions the audience naturally cares about.' }],
    ethics: ['Use theatrical deception only for lawful entertainment.', 'Do not use magic methods to obtain money, consent or consequential decisions dishonestly.', 'Credit sources and distinguish original work from historical principles.'], assignment: 'Rebuild one existing trick around a twelve-word effect statement, two convincers and a final memory test with three spectators.',
    quiz: [{ question: 'The first design step should usually be:', options: ['Buy a gimmick', 'Define the audience-facing effect', 'Add more moves', 'Explain the method'], answer: 1, explanation: 'A clear effect gives the method a purpose.' }, { question: 'Cancellation is:', options: ['Repeating the trick', 'Removing a likely explanation by structure or timing', 'Exposing the method', 'Adding props'], answer: 1, explanation: 'Cancellation quietly eliminates a suspected cause.' }], media: ['Effect-design worksheet', 'Before/after routine demonstration', 'Spectator-memory interview']
  },
  {
    id: 2, title: 'Attention, Timing and Natural Misdirection', summary: 'Control when secret actions matter by understanding gaze, motivation, offbeats, questions and natural handling.', duration: '45–60 min', level: 'Foundation',
    objectives: ['Separate direction of attention from mere distraction.', 'Place secret actions on natural offbeats.', 'Give every movement an innocent reason.'],
    sections: [{ heading: 'Attention follows meaning', body: ['People do not record every motion equally. They follow faces, questions, decisions and moments that seem important. The strongest misdirection often comes from making the secret action psychologically unimportant.', 'A question can turn attention inward while an applause moment or laugh creates an offbeat. Use these naturally rather than waving a hand or demanding that someone look away.'] }, { heading: 'Motivated movement', body: ['Every action should have a visible reason: square the papers because they are untidy, move the glass to create space, pick up the pen because the participant needs it.', 'When a secret action and an innocent action are fused, the audience remembers the innocent purpose. Rehearse the reason as carefully as the mechanics.'] }],
    procedure: ['Choose one secret action.', 'Identify when the audience currently watches it most closely.', 'Move it to a natural question, laugh, decision or transition.', 'Add an innocent physical reason for the movement.', 'Practise looking at the participant rather than the secret action.', 'Film from spectator eye level.', 'Remove any theatrical gesture that announces misdirection.'], script: ['Hold that thought for a second—what made you change your mind?', 'Place yours here. I will clear these away so we can focus on one thing.'], drills: ['Transfer a small object during a conversational question.', 'Rehearse the same switch quickly, slowly and casually to find the least suspicious timing.'], troubleshooting: [{ problem: 'You speed up during the secret move.', response: 'Keep the same rhythm before, during and after it.' }, { problem: 'Your eyes betray the method.', response: 'Rehearse where you look and what you say at the exact secret moment.' }], ethics: ['Use attention management for performance, not theft or coercion.', 'Do not create unsafe distractions in public spaces.', 'Respect spectators who do not want to participate.'], assignment: 'Film one routine twice: first with technical focus, then with deliberate gaze, motivation and offbeat timing. Compare which version looks more natural.',
    quiz: [{ question: 'Strong misdirection usually means:', options: ['Making people look away by force', 'Making the secret action unimportant', 'Moving faster', 'Adding noise'], answer: 1, explanation: 'Natural attention control is stronger than obvious distraction.' }, { question: 'A motivated action has:', options: ['A visible innocent reason', 'No purpose', 'A secret explanation', 'Maximum speed'], answer: 0, explanation: 'An innocent reason makes handling feel natural.' }], media: ['Gaze demonstration', 'Offbeat timing examples', 'Video self-review checklist']
  },
  {
    id: 3, title: 'Forces, Glimpses, Switches and Outs', summary: 'Build a utility toolbox for controlled choices, secretly acquired information, object changes and graceful failure recovery.', duration: '55–70 min', level: 'Foundation',
    objectives: ['Understand force versus free selection.', 'Use glimpses and switches only when motivated.', 'Design at least one out before performance.'],
    sections: [{ heading: 'Control without looking controlling', body: ['A force controls an outcome while preserving the experience of choice. The method may be physical, procedural, verbal or psychological. Judge a force by how free the decision feels, not how clever the mechanics are.', 'A glimpse secretly acquires information. A switch changes one object for another. Both are strongest when buried inside an action the audience already expects.'] }, { heading: 'Outs are part of the method', body: ['An out is not an apology after failure; it is a planned alternate ending. Multiple predictions, ambiguous wording, equivoque or a secondary reveal can turn uncertain methods into reliable routines.', 'Do not pile on so many outs that the procedure becomes suspicious. Choose one clean fallback that preserves the effect.'] }],
    procedure: ['Choose one desired outcome.', 'Design a direct force or controlled choice.', 'Identify the most motivated moment for a glimpse or switch.', 'Write one alternate ending.', 'Rehearse both the ideal and miss paths.', 'Test whether a spectator can describe where the choice became restricted.'], script: ['Take any one that feels right; there is no need to explain your reason.', 'We will commit to that. I had a second thought before we began, so let us see whether either possibility mattered.'], drills: ['Practise one physical force and one verbal force.', 'Perform the miss path deliberately until it feels as confident as the hit path.'], troubleshooting: [{ problem: 'The force feels like an instruction.', response: 'Remove restrictive wording and give the spectator a genuine reason to handle the objects.' }, { problem: 'Your out sounds like an excuse.', response: 'Introduce its premise before the outcome is known.' }], ethics: ['Do not use forced choices in gambling, sales or consequential decisions.', 'Keep alternate endings honest within the theatrical premise.', 'Do not pressure a spectator who resists a procedure.'], assignment: 'Create a three-minute prediction routine with one force, one motivated secret action and one pre-rehearsed out.',
    quiz: [{ question: 'A force is successful when:', options: ['The mechanics are difficult', 'The choice feels free', 'The spectator obeys quickly', 'The performer explains it'], answer: 1, explanation: 'Audience experience matters more than technical cleverness.' }, { question: 'An out should ideally be:', options: ['Invented after failure', 'Planned in advance', 'An apology', 'More complicated than the main method'], answer: 1, explanation: 'Pre-planned outs remain confident and coherent.' }], media: ['Force comparison demo', 'Switch timing clip', 'Out-design worksheet']
  },
  {
    id: 4, title: 'The Swami Gimmick and Secret Writing', summary: 'Master nail-writer style secret writing for numbers, symbols and compact predictions while keeping the handling natural.', duration: '60–80 min', level: 'Intermediate',
    objectives: ['Write legibly with minimal movement.', 'Choose information suited to secret writing.', 'Time the final writing action so it disappears inside the routine.'],
    sections: [{ heading: 'Why late writing is powerful', body: ['A secret writer allows information to be added after the spectator believes the prediction was committed. The strength comes from temporal distance: the audience remembers the paper existing before the choice and does not suspect that the final information was written later.', 'Begin with digits and simple marks. Long words create more movement and greater risk. Professional use is usually economical: one digit, one symbol, one short completion.'] }, { heading: 'Surface, grip and reveal', body: ['The writing surface must offer enough resistance while allowing the hand to remain natural. The prediction should be held for a reason—reading it, opening it, placing it down—not merely to create a writing opportunity.', 'After secret writing, reveal without immediately staring at the exact area you altered. Give the audience a beat to register the impossibility rather than rushing to prove it.'] }],
    procedure: ['Practise straight lines and curves without looking at the hand.', 'Write digits 0–9 repeatedly until size is consistent.', 'Progress to two-digit numbers and simple ESP-style symbols.', 'Rehearse writing during a justified handling action.', 'Video the hand from front and side angles.', 'Build a routine where only the final small piece of information must be added.', 'Rehearse the reveal after the writing hand has relaxed.'], script: ['I will commit to most of this before you decide; the final detail is the one that should make no sense.', 'Name the number clearly. I do not want ambiguity later.'], drills: ['Fill one page with blind digit practice.', 'Perform a one-digit prediction ten times without changing hand rhythm.'], troubleshooting: [{ problem: 'Writing is too large or illegible.', response: 'Reduce the required information and standardise digit size before performing.' }, { problem: 'The hand freezes during the secret action.', response: 'Embed writing inside a rehearsed ordinary movement and keep breathing and speech continuous.' }], ethics: ['Use secret writing for entertainment, not forged signatures, documents or fraudulent records.', 'Do not claim genuine psychic certainty outside a theatrical context.', 'Credit the historical principle and do not copy proprietary commercial routines.'], assignment: 'Build and film a prediction where a single secretly written digit converts a broad statement into an exact hit.',
    quiz: [{ question: 'The strongest secret-writing target is usually:', options: ['A paragraph', 'A compact digit or symbol', 'A signature', 'A legal document'], answer: 1, explanation: 'Small information minimises movement and risk.' }, { question: 'Late writing is deceptive mainly because of:', options: ['Speed', 'Temporal separation from the apparent commitment', 'Expensive props', 'Loud patter'], answer: 1, explanation: 'The audience remembers the prediction as already fixed.' }], media: ['Macro swami handling video', 'Printable digit drills', 'Front/side angle comparison']
  },
  {
    id: 5, title: 'Psychic Sketch Artist: Drawing Revelations', summary: 'Create convincing thought-drawing effects through controlled choice, secret information and progressive revelation without copying proprietary commercial gimmicks.', duration: '65–85 min', level: 'Intermediate',
    objectives: ['Use three different method families for drawing revelation.', 'Reveal structure before exact identity.', 'Make the final drawing feel received rather than copied.'],
    sections: [{ heading: 'Three routes to the effect', body: ['A drawing duplication can be built from a restricted or forced drawing universe, a secretly acquired glimpse or impression, or a layered combination in which only part of the information is known in advance.', 'The method should fit the presentation. A force works well for a quick experiment; a peek supports a genuinely free drawing; a layered routine allows partial hits and stronger theatre.'] }, { heading: 'Progressive revelation', body: ['Do not immediately draw the exact object. Reveal broad properties first: curved or angular, living or manufactured, tall or wide, then one distinctive feature.', 'A slightly imperfect drawing can feel more like thought transmission than a photographic copy. Let the spectator recognise the idea before displaying the final match.'] }],
    procedure: ['Set a clear drawing rule: simple object, recognisable silhouette, no words.', 'Choose whether the method is force, peek/impression or layered restriction.', 'Acquire or control only the information needed.', 'Reveal category and shape before identity.', 'Draw in stages while looking away from the spectator’s original.', 'Pause before the final distinctive feature.', 'Display both drawings together only at the climax.'], script: ['Do not make it artistic. Give me something simple enough that the shape could exist in your mind more strongly than on the paper.', 'I am getting something wider than it is tall, mostly curved, and there is one feature that breaks the symmetry.'], drills: ['Practise progressive reveals for twenty common simple drawings.', 'Sketch each object in under ten seconds using only structural lines.'], troubleshooting: [{ problem: 'The duplication looks too exact and copied.', response: 'Reveal properties verbally first and draw a rough interpretive version.' }, { problem: 'The participant chooses an elaborate scene.', response: 'Set the simple-object rule before they begin and explain that complexity weakens the experiment.' }], ethics: ['Do not reproduce proprietary gimmick construction or scripts from commercial creators.', 'Frame mind-reading claims as performance, not proof of paranormal ability.', 'Avoid secretly retaining private participant drawings.'], assignment: 'Develop three versions of one drawing-duplication effect: force-based, information-based and progressive-revelation based.',
    quiz: [{ question: 'A strong progressive reveal usually begins with:', options: ['Exact object name', 'Broad structural properties', 'The secret method', 'A long drawing'], answer: 1, explanation: 'Broad-to-specific revelation feels like information arriving gradually.' }, { question: 'An imperfect final sketch can help because it:', options: ['Looks incompetent', 'Feels more like interpretation than copying', 'Hides the paper', 'Forces the drawing'], answer: 1, explanation: 'Interpretive similarity often strengthens the thought-reading premise.' }], media: ['Three-method comparison', 'Drawing practice deck', 'Progressive-reveal demo']
  },
  {
    id: 6, title: 'One-Ahead and Sequential Revelations', summary: 'Use the one-ahead principle to reveal multiple thoughts while secretly staying one item ahead of the audience.', duration: '55–70 min', level: 'Intermediate',
    objectives: ['Understand the information-flow logic.', 'Disguise acquisition and revelation phases.', 'End with the strongest item cleanly.'],
    sections: [{ heading: 'The information engine', body: ['One-ahead works because the information apparently being revealed is not always the information secretly acquired at that moment. Each revelation creates an opportunity to learn the next item.', 'The audience should experience separate moments of insight, not a repetitive procedural cycle. Vary how each item is revealed: drawing, description, initial, exact word or prediction.'] }, { heading: 'Closing the loop', body: ['The first and final items require special handling because the chain must begin and end. Pre-knowledge, a force, a switch or a prepared final revelation can solve those edges.', 'Design the last revelation to be the most impossible and clean. If the ending requires suspicious cleanup, restructure the sequence.'] }],
    procedure: ['Map what you know before each reveal.', 'Mark where the next item is secretly learned.', 'Give each reveal a different presentation texture.', 'Use a prepared or forced item to begin if needed.', 'Arrange the strongest information last.', 'Rehearse the chain out of order so you understand the logic rather than memorising words.'], script: ['I will take these one at a time because each thought feels different; do not help me by reacting too early.', 'The first impression was vague. This final one is much clearer, so commit to it before I say anything.'], drills: ['Write the secret information state after every beat of a three-person routine.', 'Practise recovering if two participants write similar answers.'], troubleshooting: [{ problem: 'You lose track of which item you know.', response: 'Use a physical or verbal indexing system and rehearse the information map.' }, { problem: 'Every reveal feels identical.', response: 'Change modality: describe one, draw one, spell one and predict one.'] }], ethics: ['Use consenting participants and harmless information.', 'Do not use secret information to embarrass or expose someone.', 'Credit the classical principle when teaching or publishing.'], assignment: 'Construct a three-person routine using drawings, words or memories and diagram every secret information transition.',
    quiz: [{ question: 'One-ahead works by:', options: ['Guessing all items', 'Revealing one item while acquiring information about another', 'Marked cards only', 'Audience stooges'], answer: 1, explanation: 'The secret information flow is offset from the apparent reveal.' }, { question: 'The ending should ideally:', options: ['Need obvious cleanup', 'Be the strongest and cleanest reveal', 'Explain the method', 'Repeat the first reveal'], answer: 1, explanation: 'A clean final revelation determines the remembered climax.' }], media: ['Information-flow animation', 'Three-person demo', 'Routine mapping worksheet']
  },
  {
    id: 7, title: 'Billets, Folds, Peeks and Secret Information', summary: 'Handle folded paper naturally so hidden information can be controlled, glimpsed, switched or destroyed without making the paper itself suspicious.', duration: '65–85 min', level: 'Intermediate',
    objectives: ['Standardise folds and orientation.', 'Acquire information during motivated actions.', 'Separate the moment of information acquisition from the later revelation.'],
    sections: [{ heading: 'Paper as an ordinary object', body: ['Billet work is strongest when the paper feels disposable and unimportant. Use a consistent size, clear writing instructions and a fold that the participant can execute without confusion.', 'Orientation matters. Tiny asymmetries, fold directions or handling positions can tell you which side contains writing without openly inspecting it.'] }, { heading: 'Time separation', body: ['A peek is most deceptive when nothing important happens immediately afterward. Acquire information during folding, tearing, placing away or another justified action, then talk about something else before revealing it.', 'The longer the causal distance between writing and revelation, the less likely the audience is to connect the two events.'] }],
    procedure: ['Choose one paper size and fold sequence.', 'Practise orienting the billet by touch and sight.', 'Choose one motivated action for information acquisition.', 'Delay the reveal with an unrelated beat.', 'Reveal broad information before specifics.', 'Return or destroy the paper cleanly according to the routine.', 'Reset everything before the next participant.'], script: ['Write one simple thing and fold it so there is no temptation for me to see it.', 'Put that away for now. I want to understand why you chose it before I try to say what it is.'], drills: ['Fold and orient twenty billets without looking down.', 'Practise a full revelation two minutes after the secret information is acquired.'], troubleshooting: [{ problem: 'The participant folds unpredictably.', response: 'Demonstrate the fold on a blank paper first or choose a method tolerant of orientation.' }, { problem: 'You reveal the exact word immediately after handling the billet.', response: 'Insert time separation and progressive revelation.'] }],
    ethics: ['Use billets only with information participants knowingly provide for the performance.', 'Do not retain private written information without permission.', 'Do not use peeks for passwords, financial data or confidential material.'], assignment: 'Create a billet routine where the paper is out of play for at least one minute before the exact revelation.',
    quiz: [{ question: 'A strong peek is usually followed by:', options: ['Immediate exact revelation', 'Time separation', 'Method explanation', 'More suspicious handling'], answer: 1, explanation: 'Distance weakens the perceived causal link.' }, { question: 'Billet orientation helps you:', options: ['Read minds', 'Know where the writing lies without obvious inspection', 'Force a card', 'Create sound'], answer: 1, explanation: 'Consistent folds make handling reliable.' }], media: ['Fold diagrams', 'Angle-safe handling video', 'Billet practice sheets']
  },
  {
    id: 8, title: 'Book Tests and Impossible Words', summary: 'Design word revelations using controlled pages, known text, glimpses, restricted choices and layered verbal revelation.', duration: '60–80 min', level: 'Intermediate',
    objectives: ['Understand major book-test method families.', 'Make selection procedures feel literary rather than mathematical.', 'Reveal meaning and imagery before spelling.'],
    sections: [{ heading: 'Method families', body: ['Book tests can use forced pages or words, known text, secret glimpses, duplicate information, specially prepared books or structured restrictions. The method matters less than preserving the feeling that the participant encountered a genuinely free word.', 'Ordinary-looking books and simple instructions usually outperform elaborate props. Avoid page-counting procedures that feel like puzzles unless the presentation justifies them.'] }, { heading: 'Reveal the word as a thought', body: ['Instead of immediately guessing letters, describe the word’s category, emotional tone, image or sound. Exact letters then become a climax rather than an interrogation.', 'When possible involve different spectators in choosing the book, location and remembered word. Distributed decisions make the final revelation feel less controlled.'] }],
    procedure: ['Select a method family suitable for your environment.', 'Reduce instructions to the fewest necessary steps.', 'Have the participant remember rather than announce the target.', 'Reveal category or associated image.', 'Add one letter or phonetic clue.', 'State or write the exact word last.', 'Return the book to ordinary use immediately.'], script: ['Do not choose a word because it looks unusual. Let your eyes land naturally and remember the first ordinary word that catches you.', 'I do not want letters yet. The thought feels like an object rather than an action, something you could hold.'], drills: ['Take twenty random nouns and practise category-to-letter progressive reveals.', 'Rewrite a procedural book test to remove two unnecessary instructions.'], troubleshooting: [{ problem: 'The selection feels forced by arithmetic.', response: 'Change method or justify the procedure inside a clear story.' }, { problem: 'The reveal becomes twenty questions.', response: 'Use information you already know to make declarative progressive statements.'] }], ethics: ['Do not reproduce copyrighted proprietary book-test designs without permission.', 'Use ordinary published books lawfully.', 'Do not claim the method proves supernatural ability.'], assignment: 'Design a three-spectator book test in which different people influence the book, location and final remembered word.',
    quiz: [{ question: 'A stronger word reveal usually begins with:', options: ['Spelling every letter', 'Meaning, category or imagery', 'Explaining the method', 'Counting pages aloud'], answer: 1, explanation: 'Meaning-first revelation resembles thought interpretation rather than guessing.' }, { question: 'Distributed decisions can strengthen the effect because:', options: ['They make it longer', 'Control appears spread across participants', 'They expose the method', 'They remove the book'], answer: 1, explanation: 'No single procedure appears to determine the outcome.' }], media: ['Book-test method map', 'Progressive word demo', 'Selection-procedure worksheet']
  },
  {
    id: 9, title: 'Predictions, Multiple Outs and Impossible Locations', summary: 'Make predictions feel committed early while secretly preserving reliable alternate endings and strong reveal locations.', duration: '60–80 min', level: 'Intermediate',
    objectives: ['Create believable early commitment.', 'Use physical and verbal outs sparingly.', 'Choose reveal locations that add meaning rather than clutter.'],
    sections: [{ heading: 'Commitment is a perception', body: ['A prediction feels fixed when the audience believes it was isolated before the decision. Visibility, distance, another spectator’s custody or a clear timestamp can all create that perception.', 'The prediction need not be theatrically emphasised from the start. Often the strongest handling introduces it casually, then lets the audience forget it until the climax.'] }, { heading: 'Outs and locations', body: ['Multiple outs can exist as indexed cards, nested envelopes, alternate lines, objects in different locations or predictions with deliberately flexible structure.', 'The reveal location should support the story: a travel prediction in a postcard, a childhood memory inside an old photograph, a number inside a receipt. The location itself can become part of the impossibility.'] }],
    procedure: ['Define the decision to be predicted.', 'Choose how the prediction appears committed.', 'Create the primary outcome.', 'Design one or more clean outs.', 'Hide the branching before the decision.', 'Rehearse every reveal with equal confidence.', 'Remove any extra envelope or container that exists only to look mysterious.'], script: ['I wrote one possibility earlier and put it somewhere that would be awkward to change. We can ignore it until the end.', 'You made three decisions for three different reasons. Open the place that has been in view from the start.'], drills: ['Build a three-out index and retrieve each outcome without hesitation.', 'Create five prediction locations matched thematically to five subjects.'], troubleshooting: [{ problem: 'The prediction is overemphasised early.', response: 'Introduce it casually and let attention move elsewhere.' }, { problem: 'Different outs require visibly different handling.', response: 'Standardise the retrieval and reveal sequence so every outcome looks the same.'] }], ethics: ['Do not use prediction methods to imply certainty about health, death, investment or legal outcomes.', 'Avoid gambling contexts where hidden outs create real financial harm.', 'Keep claims inside entertainment.'], assignment: 'Create a prediction routine with three possible outcomes and one reveal location that has a meaningful connection to the subject.',
    quiz: [{ question: 'A prediction feels committed when:', options: ['It is mentioned constantly', 'The audience believes it was isolated before the choice', 'It uses many envelopes', 'It is expensive'], answer: 1, explanation: 'Perceived temporal and physical commitment creates impossibility.' }, { question: 'A good reveal location should:', options: ['Be arbitrary', 'Support the story or subject', 'Always be a box', 'Require long setup'], answer: 1, explanation: 'Meaningful locations add emotional logic.' }], media: ['Multiple-out index demo', 'Prediction-location gallery', 'Commitment timeline diagram']
  },
  {
    id: 10, title: 'Psychokinesis and Haunted Objects', summary: 'Create safe apparent movement using balance, thread, magnets, static, thermal effects, timing and ideomotor presentation.', duration: '65–85 min', level: 'Intermediate',
    objectives: ['Match movement methods to environment.', 'Control angles and environmental variables.', 'Frame movement as mystery without unsafe paranormal claims.'],
    sections: [{ heading: 'Movement needs conditions', body: ['Tiny physical forces become dramatic when an object is delicately balanced. Concealed thread, magnets, static charge, gradual heat effects and ordinary gravity can all create apparent animation when conditions are controlled.', 'Choose methods that are safe for the object, environment and audience. Avoid flames, strong magnets near sensitive devices or anything that could injure someone.'] }, { heading: 'Theatrical restraint', body: ['Small slow movement often looks more impossible than large obvious movement. Give the object a reason to matter before it moves: a borrowed key, old photograph, ring or written question.', 'Do not stare at the secret method. Let the audience discover the movement and allow silence to do part of the performance.'] }],
    procedure: ['Choose a lightweight or balanced object.', 'Identify environmental risks such as airflow or lighting.', 'Select a safe movement method.', 'Rehearse angles from every spectator position.', 'Introduce an emotional or narrative reason for the object.', 'Trigger the smallest convincing movement.', 'End before repeated demonstrations expose conditions.'], script: ['Do not watch my hands. Watch the object and tell me the instant anything changes.', 'Old objects are useful because people project stories onto them. Whether that matters or not, give this one your full attention.'], drills: ['Test one balanced-object effect under three lighting conditions.', 'Practise a routine where the movement occurs while your hands are visibly still and attention is on the object.'], troubleshooting: [{ problem: 'The object moves too much.', response: 'Reduce force or rebalance; subtle motion looks less mechanical.' }, { problem: 'Airflow causes inconsistent results.', response: 'Change location or choose a method less sensitive to environmental movement.'] }], ethics: ['Use only safe materials and avoid uncontrolled flame or hazardous chemicals.', 'Do not use strong magnets near implanted medical devices or sensitive electronics.', 'Present paranormal framing as theatre, not evidence.'], assignment: 'Develop a two-minute haunted-object piece with one controlled movement, one story beat and no repeated proving.',
    quiz: [{ question: 'For PK-style effects, small movement is often stronger because it:', options: ['Is easier to miss', 'Looks less mechanical and more uncanny', 'Requires shouting', 'Needs no rehearsal'], answer: 1, explanation: 'Subtle movement can feel spontaneous and inexplicable.' }, { question: 'Environmental control matters because:', options: ['Airflow and lighting can expose or alter methods', 'It makes props expensive', 'It removes story', 'It guarantees paranormal power'], answer: 0, explanation: 'Physical methods depend on conditions and angles.' }], media: ['Safe method overview', 'Angle test video', 'Haunted-key performance']
  },
  {
    id: 11, title: 'Spirit Writing, Ashes and Hidden Messages', summary: 'Design eerie visual revelations with safe hidden-writing, condensation, heat-reveal and surface-transfer principles.', duration: '55–75 min', level: 'Intermediate',
    objectives: ['Choose safe message-reveal methods.', 'Control timing so the appearance feels impossible.', 'Avoid hazardous chemicals and uncontrolled flame.'],
    sections: [{ heading: 'The revelation is the effect', body: ['A message that gradually appears can be stronger than an instantaneous switch because the audience watches the impossibility develop. Condensation, safe heat-reveal materials, powder or surface-transfer effects can create theatrical writing when prepared carefully.', 'Use familiar household-safe materials and test them beforehand. Never improvise unknown chemicals on skin, food, drink or surfaces that could be damaged.'] }, { heading: 'Story gives the message weight', body: ['A hidden message should answer a question or complete a narrative rather than merely display a random word. The strongest reveals connect to a choice made moments earlier.', 'Keep the message short. A symbol, initial, date or one-word response is easier to reveal cleanly and more mysterious than a paragraph.'] }],
    procedure: ['Choose a short meaningful target message.', 'Select a tested non-toxic reveal principle.', 'Prepare the surface away from the audience.', 'Build a reason for the surface to enter the routine.', 'Trigger the reveal at a clear dramatic beat.', 'Allow the audience to read it before speaking.', 'Dispose of or clean materials safely.'], script: ['Nothing is written here that you can see now. Hold on to the question rather than saying it again.', 'Do not touch it yet. Let the image finish appearing before we decide whether it means anything.'], drills: ['Test message size and contrast under normal room lighting.', 'Create three one-word reveals tied to three different story premises.'], troubleshooting: [{ problem: 'The writing appears too early.', response: 'Change preparation, environment or trigger timing before performing.' }, { problem: 'The reveal is faint.', response: 'Increase contrast safely rather than adding untested material.'] }],
    ethics: ['Do not use unknown chemicals, irritants or substances on skin.', 'Avoid uncontrolled flame and heat near participants.', 'Do not imply spirit communication to exploit grief or vulnerability.'], assignment: 'Create one safe hidden-message effect whose final word directly answers a spectator-generated fictional question.',
    quiz: [{ question: 'The best hidden message is usually:', options: ['Long', 'Short and meaningful', 'Chemically complex', 'Unrelated'], answer: 1, explanation: 'Compact messages reveal more reliably and carry clearer theatrical meaning.' }, { question: 'If a material has not been safety-tested you should:', options: ['Use less', 'Avoid it', 'Put it on skin', 'Heat it'], answer: 1, explanation: 'Unknown materials are not appropriate for performance experimentation.' }], media: ['Safe reveal-method matrix', 'Message timing video', 'Surface test worksheet']
  },
  {
    id: 12, title: 'ESP Symbols and Strange Coincidences', summary: 'Use simple symbols, controlled choices, stacks, markings and matching structures to create increasingly impossible coincidences.', duration: '55–70 min', level: 'Intermediate',
    objectives: ['Structure coincidence effects in phases.', 'Use symbol systems that are easy to recognise.', 'Shift the climax from performer skill to participant intuition.'],
    sections: [{ heading: 'Why simple symbols work', body: ['Simple geometric or original symbol sets are visually memorable, language-light and easy to reveal. They can support forces, predictions, matching effects and participant-as-mind-reader presentations.', 'Create your own symbol artwork rather than copying proprietary card designs. The method should survive ordinary handling and clear lighting.'] }, { heading: 'Escalating coincidence', body: ['A coincidence routine becomes stronger when each phase seems to remove an explanation. First the performer matches a participant, then two participants match each other, then a prediction was committed beforehand.', 'Vary the method across phases when possible. Method diversity prevents the audience from correctly applying one explanation to every effect.'] }],
    procedure: ['Choose five clear original symbols.', 'Decide which phase uses force, control, marking or prediction.', 'Begin with a quick low-stakes match.', 'Shift agency to the participant.', 'Escalate to a pre-committed final prediction.', 'Keep handling identical across outcomes.', 'End before the coincidence becomes repetitive.'], script: ['This time I will not try to read you. You will make the decision and someone else will try to match it.', 'If the final pair matches as well, the strange part is that neither of you knew the prediction was already here.'], drills: ['Draw all symbols consistently from memory.', 'Create a three-phase routine using at least two different secret principles.'], troubleshooting: [{ problem: 'The symbols are too similar.', response: 'Redesign them for immediate recognition and distinct silhouettes.' }, { problem: 'Every phase uses the same force.', response: 'Change method or presentation so repeated handling does not expose the pattern.'] }], ethics: ['Use original printable artwork or public-domain symbols.', 'Do not market ESP routines as scientific proof of psychic ability.', 'Avoid claims about diagnosing intuition or personality.'], assignment: 'Build a three-phase coincidence routine that ends with a prediction and includes a participant-as-mind-reader middle phase.',
    quiz: [{ question: 'A strong multi-phase routine should:', options: ['Repeat one obvious method', 'Escalate conditions and vary explanations', 'Use more cards every time', 'Explain the stack'], answer: 1, explanation: 'Escalation and method diversity strengthen impossibility.' }, { question: 'Participant-as-mind-reader framing helps because:', options: ['It changes the source of apparent ability', 'It exposes the method', 'It removes suspense', 'It requires no structure'], answer: 0, explanation: 'Agency shifts away from the performer and creates a different experience.' }], media: ['Printable original symbol deck', 'Three-phase routine demo', 'Symbol design template']
  },
  {
    id: 13, title: 'Bizarre Magic and Story-Based Mysteries', summary: 'Transform methods into memorable strange stories using objects, photographs, letters, psychometry themes and restrained atmosphere.', duration: '60–80 min', level: 'Advanced',
    objectives: ['Give props a narrative reason to exist.', 'Use atmosphere without overacting.', 'Tie the final revelation back to an earlier story detail.'],
    sections: [{ heading: 'Object first, mythology second', body: ['Bizarre magic works when the object appears to have a history: an old key, photograph, letter, coin or notebook. The story should explain why the audience is looking at it, not bury the effect under lore.', 'Use specific sensory details—date, place, handwriting, wear—rather than pages of exposition. Let the spectator infer more than you explicitly state.'] }, { heading: 'Callback structure', body: ['Plant a small detail early that seems decorative, then make it essential at the climax. A name on a photograph, a phrase in a letter or a symbol scratched into an object can return as the final impossible link.', 'The method can remain simple because the story carries memory and emotion. Do not confuse emotional impact with exploiting genuine grief or trauma.'] }],
    procedure: ['Choose one ordinary object with visual character.', 'Write a two-sentence fictional history.', 'Identify one detail to plant early.', 'Select a simple method that can reveal or transform that detail.', 'Remove any story sentence that does not affect mood or method.', 'Perform the effect before explaining the full backstory.', 'End on the callback and silence.'], script: ['This photograph came with one sentence written on the back. I will not show you that sentence yet because it may bias the choice.', 'You mentioned the window without seeing the note. Turn the photograph over now.'], drills: ['Tell the same object story in thirty seconds, one minute and three minutes.', 'Create five callbacks that turn a decorative detail into the final reveal.'], troubleshooting: [{ problem: 'The story overwhelms the magic.', response: 'Cut exposition until the audience can state the central mystery in one sentence.' }, { problem: 'The performance feels melodramatic.', response: 'Lower vocal intensity and let the object and reveal provide atmosphere.'] }], ethics: ['Keep haunted histories fictional or clearly theatrical.', 'Do not exploit bereavement or claim contact with specific deceased people.', 'Avoid using culturally sacred objects disrespectfully.'], assignment: 'Create a five-minute story-based routine using one photograph or ordinary old object, one planted detail and one final callback.',
    quiz: [{ question: 'A strong bizarre-magic story should primarily:', options: ['Show how much lore you wrote', 'Give the object and effect meaning', 'Hide weak pacing', 'Claim real spirits'], answer: 1, explanation: 'Narrative should serve the experience, not replace it.' }, { question: 'A callback is:', options: ['Repeating the method', 'Returning to an earlier detail at the climax', 'A phone call', 'Explaining the prop'], answer: 1, explanation: 'Callbacks make the ending feel inevitable and connected.' }], media: ['Haunted-photograph performance', 'Story trimming worksheet', 'Callback examples']
  },
  {
    id: 14, title: 'Designing Your Own Gimmicks and Systems', summary: 'Engineer practical secret tools around reliability, innocence, reset, angles, durability and emergency outs instead of cloning commercial products.', duration: '70–90 min', level: 'Advanced',
    objectives: ['Translate an effect requirement into a mechanical design.', 'Prototype for reliability before invisibility.', 'Evaluate reset, noise, angles, pocket management and failure states.'],
    sections: [{ heading: 'Design from the impossible sentence', body: ['Begin with what the gimmick must secretly accomplish: add one mark, acquire one impression, index several predictions, hold a billet, move a lightweight object or exchange one item for another.', 'Do not begin by copying a commercial device. Historical principles can inspire original engineering, but proprietary construction should remain the creator’s work.'] }, { heading: 'Reliability beats cleverness', body: ['A gimmick that works nine times out of ten is not performance-ready if the failure is visible. Simplify moving parts, make reset obvious and build a graceful out for the most likely failure.', 'Test noise, lighting, spectator angles, clothing, pocket access and transport. The method should survive the real environment rather than only a desk rehearsal.'] }],
    procedure: ['Write one hidden function the gimmick must perform.', 'Sketch three mechanically different ways to achieve it.', 'Choose the simplest prototype.', 'Test fifty repetitions for reliability.', 'Measure reset time and angle sensitivity.', 'Create one emergency out.', 'Refine appearance only after function is dependable.', 'Document safe materials and storage.'], script: ['The prop should never need an explanation. If I have to tell the audience why it is normal, the design probably is not finished.', 'I am testing the failure case first; success is useful only after I know what happens when the mechanism does not cooperate.'], drills: ['Prototype a billet holder from ordinary craft materials.', 'Design a prediction index on paper before building any physical version.'], troubleshooting: [{ problem: 'The prototype is clever but unreliable.', response: 'Remove features until the core function works repeatedly under realistic conditions.' }, { problem: 'The gimmick requires suspicious handling.', response: 'Redesign access around an action the performer already needs to perform.'] }], ethics: ['Do not clone patented, proprietary or currently marketed gimmick construction for resale.', 'Avoid hazardous materials, sharp edges, high heat or strong magnets around vulnerable devices.', 'Credit historical inspirations in teaching notes.'], assignment: 'Prototype one original utility device, log fifty tests and write a failure-mode checklist before considering performance use.',
    quiz: [{ question: 'The first gimmick-design question is:', options: ['What can I copy?', 'What secret function must be achieved?', 'What colour should it be?', 'How expensive is it?'], answer: 1, explanation: 'Function determines engineering.' }, { question: 'A prototype should be beautified:', options: ['Before testing', 'After reliability is established', 'Instead of testing', 'Only after sale'], answer: 1, explanation: 'Reliable function comes before cosmetic refinement.' }], media: ['Prototype worksheet', 'Reliability test log', 'Original-design case study']
  },
  {
    id: 15, title: 'Build a Seven-Minute Esoteric Magic Act', summary: 'Combine a thought effect, drawing revelation, strange object and impossible prediction into one escalating act with callbacks and clean pacing.', duration: '80–100 min', level: 'Capstone',
    objectives: ['Sequence effects so methods and textures vary.', 'Use callbacks to unify the set.', 'Design reset, pocket management and failure recovery.'],
    sections: [{ heading: 'Escalation rather than collection', body: ['A short act should feel like one journey, not four unrelated tricks. Begin with a fast low-procedure mystery, move into a participatory thought or drawing effect, introduce one visually strange object and finish with the strongest pre-committed prediction.', 'Vary method families. If every effect uses folded paper, spectators will search for one paper-based explanation. Contrast no-prop framing, writing, object movement and prediction.'] }, { heading: 'Callbacks and ending', body: ['Plant one detail in the opener that returns in the final prediction. A symbol, phrase or colour can make the ending feel as though the entire act was planned before the audience made any choices.', 'Finish on the impossible image, not on cleanup. Pocket management, reset and disposal should be designed before rehearsal so the final moment remains undisturbed.'] }],
    procedure: ['Choose four effects with different textures.', 'Order them from shortest and clearest to strongest.', 'Map every prop and pocket position.', 'Plant one callback in effect one.', 'Write transitions that justify the next prop.', 'Rehearse ideal and failure paths.', 'Film a full uninterrupted seven-minute run.', 'Ask viewers to describe the act ten minutes later.', 'Cut anything they consistently forget.'], script: ['The first symbol will seem unimportant. Keep it somewhere in the back of your mind.', 'We have used a thought, a drawing and an object. The final prediction connects the one detail none of us treated as important.'], drills: ['Perform the act with no stopping even when you simulate one failed method.', 'Rehearse pocket reset until transitions require no searching.'], troubleshooting: [{ problem: 'The act feels like four demos.', response: 'Add one premise, recurring image and callback that links the effects.' }, { problem: 'The strongest effect comes too early.', response: 'Reorder so conditions and emotional stakes escalate toward the finale.' }], ethics: ['Keep all deception inside the agreed entertainment context.', 'Protect participant dignity when an effect misses.', 'Credit creators when routines or presentations derive materially from their work.'], assignment: 'Record a polished seven-minute act, then score clarity, pacing, dead time, suspicious moments, audience participation and strength of ending.',
    quiz: [{ question: 'A cohesive act should:', options: ['Use one method repeatedly', 'Vary textures while sharing a premise', 'Contain maximum props', 'Explain every transition'], answer: 1, explanation: 'Varied methods reduce pattern detection while a shared premise creates unity.' }, { question: 'The final beat should ideally be:', options: ['Cleanup', 'The strongest impossible image', 'An apology', 'A method lecture'], answer: 1, explanation: 'End on the memory you want the audience to keep.' }], media: ['Full seven-minute model act', 'Pocket map template', 'Capstone self-review sheet']
  }
];
